# Generated by Django 4.0.4 on 2022-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('p1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p4', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'bebida',
            },
        ),
    ]
