# Generated by Django 4.0.4 on 2022-04-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('p1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p4', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'bebida',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('metodo_pag', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
                ('p1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p4', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
            options={
                'db_table': 'itensPedido',
            },
        ),
    ]
