# Generated by Django 4.0.4 on 2022-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
