# Generated by Django 4.0.4 on 2022-04-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.AddField(
            model_name='item',
            name='cat',
            field=models.SmallIntegerField(null=True),
        ),
    ]
