# Generated by Django 4.0.4 on 2022-04-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_item_categoria_item_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat',
            field=models.SmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('metodo_pag', models.CharField(max_length=50, null=True)),
                ('itens', models.ManyToManyField(to='app.item')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
    ]
